---
# defaults file for forgejo runner

# version information
forgejo_runner_version: "15"
forgejo_runner_arch: "amd64"
forgejo_runner_os: "linux"

# runner: binary
forgejo_runner_download: "https://code.forgejo.org/forgejo/runner/releases/download/v{{ forgejo_runner_version }}/forgejo-runner-{{ forgejo_runner_version }}-{{ forgejo_runner_os }}-{{ forgejo_runner_arch }}"
forgejo_runner_path: "/usr/local/bin/forgejo-runner"

forgejo_runner_user: "runner"
forgejo_runner_type: "podman"

forgejo_runner_config: "/home/{{ forgejo_runner_user }}/runner-config.yml"
forgejo_runner_unit_path: "/etc/systemd/user/forgejo-runner.service"

forgejo_runner_log_level: "info"
forgejo_runner_log_job_level: "{{ forgejo_runner_log_level }}"

forgejo_runner_concurrent: 1

forgejo_runner_timeout: "3h"
forgejo_runner_timeout_shutdown: "3h"
forgejo_runner_timeout_fetch: "30s"

forgejo_runner_interval_fetch: "2s"
forgejo_runner_interval_report: "1s"

# forgejo connection
forgejo_runner_connection_url: ""
forgejo_runner_connection_token: ""
forgejo_runner_connection_uuid: ""
