---

# systemd integration
woodpecker_server_service_dir: "/etc/containers/systemd/"
woodpecker_server_config_volume: "woodpecker-server-config"

# version infomation
woodpecker_server_version: "latest"
woodpecker_server_image: "docker.io/woodpeckerci/woodpecker-server:{{ woodpecker_server_version }}"

# database settings (only postgres is supported)
woodpecker_server_db_manage: true
woodpecker_server_db_host: "host.containers.internal"
woodpecker_server_db_name: "woodpecker"
woodpecker_server_db_user: "woodpecker_app"
#woodpecker_server_db_password: ""

woodpecker_server_db_dsn: "postgres://{{ woodpecker_server_db_user }}:{{ woodpecker_server_db_password }}@{{ woodpecker_server_db_host }}/{{ woodpecker_server_db_name }}?sslmode=disable"

# web details
woodpecker_server_web_port: 3001 # bind (host) port
woodpecker_server_web_url: "http://{{ inventory_hostname }}:{{ woodpecker_server_web_port }}/"
woodpecker_server_web_redirect: "{{ woodpecker_server_web_url }}authorize"

# Forgejo integration
woodpecker_server_forgejo_url: "{{ fg_forgejo_web_url }}"
woodpecker_server_forgejo_name: "woodpecker_ci"
woodpecker_server_forgejo_regenerate: false

# set this to manually configure oauth
#woodpecker_server_forgejo_client: ""
#woodpecker_server_forgejo_secret: ""

# registration
woodpecker_server_allow_registration: true
woodpecker_server_admins: []
# woodpecker_server_orgs: []
