---

# systemd integration
woodpecker_server_service_dir: "/etc/containers/systemd/"
woodpecker_server_config_volume: "woodpecker-server-config"

# version infomation
woodpecker_server_version: "latest"
woodpecker_server_image: "docker.io/woodpeckerci/woodpecker-server:{{ woodpecker_server_version }}"

# database settings (only postgres is supported)
woodpecker_server_db_manage: true
woodpecker_server_db_host: "host.containers.internal"
woodpecker_server_db_name: "woodpecker"
woodpecker_server_db_user: "woodpecker_app"
#woodpecker_server_db_password: ""

woodpecker_server_db_dsn: "postgres://{{ woodpecker_server_db_user }}:{{ woodpecker_server_db_password }}@{{ woodpecker_server_db_host }}/{{ woodpecker_server_db_name }}?sslmode=disable"

# web details
woodpecker_server_domain: "{{ inventory_hostname }}"

woodpecker_server_web_port: 3001 # bind (host) port
woodpecker_server_web_url: "http://{{ woodpecker_server_domain }}:{{ woodpecker_server_web_port }}/"
woodpecker_server_web_redirect: "{{ woodpecker_server_web_url }}authorize"

# should we bind to localhost?
woodpecker_server_expose_web_port: false
woodpecker_server_web_port_map: "{% if not woodpecker_server_expose_web_port %}127.0.0.1:{% endif %}{{ woodpecker_server_web_port }}"

# Forgejo integration
woodpecker_server_forgejo_url: "{{ fg_forgejo_web_url }}"
woodpecker_server_forgejo_name: "woodpecker_ci"
woodpecker_server_forgejo_regenerate: false

# set this to manually configure oauth
#woodpecker_server_forgejo_client: ""
#woodpecker_server_forgejo_secret: ""

# registration
woodpecker_server_allow_registration: true
woodpecker_server_admins: []
# woodpecker_server_orgs: []

# caddy integration
woodpecker_server_caddy: false
woodpecker_server_caddy_network: "caddy-ingress"
woodpecker_server_caddy_labels:
  caddy: "{{ woodpecker_server_domain }}:{{ woodpecker_server_port }}"
  caddy.reverse_proxy: "{% raw %}{{ upstreams 8000 }}{% endraw %}"

# reverse proxy: nginx
woodpecker_server_nginx: true
woodpecker_server_nginx_upstream: "http://127.0.0.1:{{ woodpecker_server_web_port }}"
woodpecker_server_nginx_conf: "/etc/nginx/conf.d/30-woodpecker.conf"
woodpecker_server_ssl_cert: "/etc/pki/tls/certs/{{ woodpecker_server_domain }}.pem"
woodpecker_server_ssl_key: "/etc/pki/tls/private/{{ woodpecker_server_domain }}.pem"
