---
# tasks file for forgejo

- name: Validate container engine
  ansible.builtin.assert:
    that:
      - forgejo_container_engine in ['podman']
    fail_msg: "unsupported container engine: {{ forgejo_container_engine }}"
  changed_when: false

- name: Include container engine tasks
  ansible.builtin.include_tasks: "engine_{{ forgejo_container_engine }}.yml"

- name: Ensure service is running
  become: true
  ansible.builtin.service:
    name: forgejo
    state: started
