---
# handlers file for fg_forgejo

- name: "Restart woodpecker"
  become: true
  ansible.builtin.service:
    name: woodpecker_server
    state: restarted

- name: "Reload woodpecker service"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: woodpecker_server
    state: reloaded
