---

- name: Create forgejo volume quadlet
  become: true
  containers.podman.podman_volume:
    state: quadlet
    name: forgejo-data
    quadlet_dir: "{{ fg_forgejo_service_dir }}"
  notify:
    - Reload forgejo service
    - Restart forgejo

- name: Ensure git volume exists
  become: true
  containers.podman.podman_volume:
    state: quadlet
    name: forgejo-git
    quadlet_dir: "{{ fg_forgejo_service_dir }}"
  notify:
    - Reload forgejo service
    - Restart forgejo

- name: Ensure configuration folder exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ fg_forgejo_userid }}"
    group: "{{ fg_forgejo_groupid }}"
    mode: "0500"
    setype: container_file_t
  with_items:
    - "{{ fg_forgejo_custom_dir }}"
    - "{{ fg_forgejo_custom_dir }}conf"

- name: Provide customised forgejo config
  become: true
  ansible.builtin.template:
    src: app.ini.j2
    dest: "{{ fg_forgejo_custom_dir }}/conf/app.ini"
    owner: "{{ fg_forgejo_userid }}"
    group: "{{ fg_forgejo_groupid }}"
    mode: "0400"
    setype: container_file_t
  notify:
    - Restart forgejo

- name: Create forgejo network quadlet
  become: true
  containers.podman.podman_network:
    name: "forgejo"
    state: quadlet
    quadlet_dir: "{{ fg_forgejo_service_dir }}"
  notify:
    - Reload forgejo service
    - Restart forgejo

- name: Create forgejo container quadlet
  become: true
  containers.podman.podman_container:
    name: forgejo
    image: "{{ fg_forgejo_image }}"
    state: quadlet
    network: forgejo.network
    env:
      USER_UID: "{{ fg_forgejo_userid }}"
      USER_GID: "{{ fg_forgejo_groupid }}"
      FORGEJO_CUSTOM: "/data/custom"
    ports:
      - "{{ fg_forgejo_web_port_map }}:3000"
      - "{{ fg_forgejo_ssh_port }}:22"
    volumes:
      - "forgejo-data.volume:/data"
      - "forgejo-git.volume:/data/git"
      - "{{ fg_forgejo_custom_dir }}:/data/custom:Z"
    secrets:
      - "forgejo-secret-key,uid={{ fg_forgejo_userid }}"
      - "forgejo-token-internal,uid={{ fg_forgejo_userid }}"
      - "forgejo-jwt-oauth,uid={{ fg_forgejo_userid }}"
      - "forgejo-jwt-lfs,uid={{ fg_forgejo_userid }}"
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
