---
# tasks file for fg_forgejo

- name: Setup secrets
  ansible.builtin.include_tasks: secret.yml

- name: Install forgejo
  ansible.builtin.include_tasks: install.yml

- name: Include customisations
  ansible.builtin.include_tasks: customise.yml

- name: Include database-related tasks
  ansible.builtin.include_tasks: postgres.yml
  when: fg_forgejo_db_manage

- name: Manage nginx configuration
  ansible.builtin.include_tasks: nginx.yml

- name: Ensure service is running
  become: true
  ansible.builtin.service:
    name: forgejo
    state: started

- name: Create admin user for ansible tasks
  when: fg_forgejo_token is undefined
  block:
    # create account for admin tasks
     - fossgalaxy.forge.forgejo_admin:
          auth_forgejo_url: "{{ fg_forgejo_domain }}"
          username: "{{ fg_forgejo_admin_username }}"
          email: "{{ fg_forgejo_admin_email }}"
          admin: true

- name: FreeIPA integration
  when: fg_forgejo_ldap_host is defined
  ansible.builtin.include_tasks: freeipa.yml
