---

- name: Reload Forgejo Runner
  become: true
  become_user: "{{ forgejo_runner_user }}"
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
    name: forgejo-runner
    state: restarted

- name: Restart Forgejo Runner
  become: true
  become_user: "{{ forgejo_runner_user }}"
  ansible.builtin.systemd_service:
    scope: user
    name: forgejo-runner
    state: restarted
