---

- name: Validate runner provider
  ansible.builtin.assert:
    that:
      - forgejo_runner_method in ['binary']
    fail_msg: "unsupported install method"
  changed_when: false

- name: Validate runner provider
  ansible.builtin.assert:
    that:
      - forgejo_runner_engine in ['podman']
    fail_msg: "unsupported runner engine"
  changed_when: false

- name: Include setup tasks
  ansible.builtin.include_tasks: "setup_{{ forgejo_runner_method }}.yml"
