---
# Forgejo integrations

# Mode: manually set token
- name: Create secret for oauth
  become: true
  when: woodpecker_server_forgejo_secret is defined
  containers.podman.podman_secret:
    state: present
    name: woodpecker-oauth-secret
    data: "{{ woodpecker_server_forgejo_secret }}"
