---

- name: Create agent key secret
  become: true
  containers.podman.podman_secret:
    state: present
    name: woodpecker-agent-key
    data: "{{ woodpecker_server_agent_key }}"

- name: Ensure configuration volume quadlet exists
  become: true
  containers.podman.podman_image:
    name: "{{ woodpecker_server_config_volume }}"
    state: quadlet
    quadlet_dir: "{{ woodpecker_server_service_dir }}"
  notify:
    - Reload woodpecker service

- name: Ensure container quadlet exists
  become: true
  containers.podman.podman_container:
    name: woodpecker_server
    image: "{{ woodpecker_server_image }}"
    state: quadlet
    env:
      WOODPECKER_HOST: "{{ woodpecker_server_web_url }}"
      WOODPECKER_OPEN: "{{ woodpecker_server_allow_registration }}"
      WOODPECKER_ADMIN: "{{ woodpecker_server_admins | join(',') }}"
      #WOODPECKER_ORGS: "{{ woodpecker_server_orgs | join(',') }}"
      WOODPECKER_FORGEJO: true
      WOODPECKER_FORGEJO_URL: "{{ woodpecker_server_forgejo_url }}"
      WOODPECKER_FORGEJO_CLIENT: "{{ woodpecker_server_forgejo_client }}"
      WOODPECKER_FORGEJO_SECRET_FILE: "/run/secrets/woodpecker-oauth-secret"
      WOODPECKER_DATABASE_DRIVER: postgres
      FORGEJO_CUSTOM: "/data/custom"
    ports:
      - "{{ woodpecker_server_web_port }}:8000"
    volumes:
      - "{{ woodpecker_server_config_volume }}.volume:/var/lib/woodpecker"
    secrets:
      - "woodpecker-oauth-secret"
      - "woodpecker-agent-key,type=env,target=WOODPECKER_AGENT_SECRET"
      - "woodpecker-db-dsn,type=env,target=WOODPECKER_DATABASE_DATASOURCE"
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify:
    - Reload woodpecker service
