---

# needs to be done first so we can set the client id
- name: forgejo integration
  ansible.builtin.include_tasks: forgejo.yml

- name: Install woodpecker server
  ansible.builtin.include_tasks: install.yml

- name: Include database-related tasks
  ansible.builtin.include_tasks: postgres.yml
  when: woodpecker_server_db_manage

- name: Ensure service is running
  become: true
  ansible.builtin.service:
    name: woodpecker_server
    state: started

